language: node_js
node_js:
  - lts/*
install:
  - npm install
  - gem install awesome_bot
script:
  - npm test
  - awesome_bot index.js --allow-dupe --allow-redirect --skip-save-results --request-delay 1
